variables:
  imageName: 'devopsoh/api-user'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - '/apis/userprofile/*'

stages:
- stage: A
  jobs:
  - job: A1
    pool: 'custom'
    steps:
    - script: 'echo hello world'
- stage: B
  jobs:
  - job: B1
    pool: 'custom'
    steps:
    - script: 'echo hello world2'