variables:
  imageName: 'devopsoh/api-user'
  releaseName : 'api-trip'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - '/apis/userprofile/*'

stages:
- stage: Build
  jobs:
  - job: Build
    pool: 'custom'
    steps:
    - task: Docker@2
      displayName: build $(imageName) image
      inputs:
        containerRegistry: ACR
        repository: $(imageName)
        command: build
        Dockerfile: 'apis/userprofile/Dockerfile'
    - task: Docker@2
      displayName: push $(imageName) image to ACR
      inputs:
        containerRegistry: ACR
        repository: $(imageName)
        command: push
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: 'apis/userprofile/charts/mydrive-user'  
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))    
- stage: Deploy
  jobs:
  - job: Deploy
    pool: 'custom'
    steps:
    - task: HelmInstaller@0
      displayName: 'Install Helm 2.14.3'
      inputs:
        helmVersion: 2.14.3
        checkLatestHelmVersion: false
    - task: Kubernetes@1
      displayName: 'kubectl login'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'OTA-Prod-52 (7bc13e13-9b79-4572-a6c6-2bf5af2e368b)'
        azureResourceGroup: openhackxmk9rg
        kubernetesCluster: openhackxmk9aks
        command: login
    - bash: |
        currentSlot=`(helm get values --all $(releaseName) | grep -Po 'productionSlot: \K.*')`
        if [ "$currentSlot" == "blue" ]; then
            newSlot="green"
        else
            newSlot="blue"
        fi
        
        echo "##vso[task.setvariable variable=currentSlot]$currentSlot"
        echo "##vso[task.setvariable variable=newSlot]$newSlot"
      displayName: 'Read Slots'
    - script: 'echo "currentSlot: $(currentSlot)"'      
    - script: 'echo "newSlot: $(newSlot)"'      

