variables:
  projects: 'apis/poi/**/*.csproj'
  TestProjects: './tests/UnitTests/**/*.csproj'

stages:
- stage: Build
  jobs:
  - job: Build
    pool: 'custom'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '2.2.x'
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '$(projects)'
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: '$(projects)'
        arguments: '--configuration $(BuildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        projects: 'apis/poi/tests/UnitTests/UnitTests.csproj'
        arguments: '--configuration $(BuildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: True