trigger:
  branches:
    include:
    - master
  paths:
    include:
    - '/apis/user-java/*'

stages:
- template: ../build/templates/blue_green_stage.yml
  parameters:
    releaseName: 'api-user'  
    artifactName:  'trips'
    chartPath: '$(System.DefaultWorkingDirectory)/apis/userprofile/charts/mydrive-user'   
    artifactPath: '$(Pipeline.Workspace)/$(artifactName)'
    imageName: 'devopsoh/api-user'
    dockerfilePath: 'apis/userprofile/Dockerfile'
    stagingEnvironment: 'UserProfile Staging'
    productionEnvironment: 'UserProfile Production'
    finalizeEnvironment: 'UserProfile Finalize Deployment'
    buildId: $(Build.BuildId)