trigger:
  branches:
    include:
    - master
  paths:
    include:
    - '/apis/user-java/*'

stages:
- template: ../build/templates/blue_green_stage.yml
  parameters:
    releaseName: 'api-user-java'  
    artifactName:  'userjava'
    chartPath: '$(System.DefaultWorkingDirectory)/apis/user-java/charts/mydrive-user-java'   
    artifactPath: '$(Pipeline.Workspace)/$(artifactName)'
    imageName: 'devopsoh/api-user-java'
    dockerfilePath: 'apis/user-java/Dockerfile'
    stagingEnvironment: 'UserJava Staging'
    productionEnvironment: 'UserJava Production'
    finalizeEnvironment: 'UserJava Finalize Deployment'
    buildId: $(Build.BuildId)