variables:
  imageName: 'devopsoh/api-trip'
  releaseName : 'api-trip'
  dockerfilePath: 'apis/trips/Dockerfile'
  chartPath: '$(System.DefaultWorkingDirectory)/apis/trips/charts/mydrive-trips'
  stagingEnvironment: 'Trips Staging'
  productionEnvironment: 'Trips Production'
  finalizeEnvironment: 'Trips Finalize Deployment'
  artifactName: 'trips'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - '/apis/trips/*'

stages:
- stage: Build
  jobs:
  - job: Build
    pool: 'custom'
    steps:
    - task: Docker@2
      displayName: build image
      inputs:
        containerRegistry: ACR
        repository: $(imageName)
        command: build
        Dockerfile: $(dockerfilePath)
    - task: Docker@2
      displayName: push image to ACR
      inputs:
        containerRegistry: ACR
        repository: $(imageName)
        command: push      
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  
    - publish: $(chartPath)
      artifact: $(artifactName)
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  
- stage: Staging
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  
  jobs:
  - deployment: staging
    environment: $(stagingEnvironment)
    pool: 'custom'
    strategy:
     runOnce:
      deploy:
        steps:
        - download: current
          artifact: $(artifactName) 
        - template: ../build/templates/read_slots.yml  # Template reference
          parameters:
            releaseName: $(releaseName)     
        - template: ../build/templates/helm_upgrade.yml 
          parameters:
            releaseName: $(releaseName)   
            artifactName:  $(artifactName) 
            chartPath: '$(Pipeline.Workspace)/$(artifactName)'    
            setValues: '$(newSlot).tag=$(Build.BuildId),$(newSlot).enabled=true'     
- stage: Production
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  
  jobs:
  - deployment: production
    environment: $(productionEnvironment)
    pool: 'custom'
    strategy:
     runOnce:
      deploy:
        steps:
        - download: current
          artifact: $(artifactName) 
        - template: ../build/templates/read_slots.yml 
          parameters:
            releaseName: $(releaseName)  
        - template: ../build/templates/helm_upgrade.yml 
          parameters:
            releaseName: $(releaseName)   
            artifactName:  $(artifactName) 
            chartPath: '$(Pipeline.Workspace)/$(artifactName)'    
            setValues: 'productionSlot=$(newSlot)'   
- stage: Finalize
  condition: and(always(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  
  jobs:
  - deployment: cleanup
    environment: $(finalizeEnvironment)
    pool: 'custom'
    strategy:
     runOnce:
      deploy:
        steps:
        - download: current
          artifact: $(artifactName) 
        - template: ../build/templates/read_slots.yml  
          parameters:
            releaseName: $(releaseName) 
        - template: ../build/templates/helm_upgrade.yml 
          parameters:
            releaseName: $(releaseName)   
            artifactName:  $(artifactName) 
            chartPath: '$(Pipeline.Workspace)/$(artifactName)'    
            setValues: '$(newSlot).enabled=false'
      on:
        failure:
          steps:
          - script: 'echo "rollback"'
- stage: Rollback
  condition: and(failed(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  
  jobs:
  - deployment: cleanup
    environment: 'Rollback'
    pool: 'custom'
    strategy:
     runOnce:
      deploy:
        steps:
        - download: current
          artifact: $(artifactName) 
        - template: ../build/templates/read_slots.yml 
          parameters:
            releaseName: $(releaseName) 
        - template: ../build/templates/helm_upgrade.yml 
          parameters:
            releaseName: $(releaseName)   
            artifactName:  $(artifactName) 
            chartPath: '$(Pipeline.Workspace)/$(artifactName)'    
            setValues: 'productionSlot=$(newSlot)'